apiVersion: v1
kind: Service
metadata:
  name: airtrail
  namespace: airtrail
  labels:
    app.kubernetes.io/name: airtrail
spec:
  selector:
    app.kubernetes.io/name: airtrail
  type: LoadBalancer
  loadBalancerIP: 192.168.10.224
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 3000
      name: web
