apiVersion: v1
kind: Service
metadata:
  name: affine
  namespace: affine
  labels:
    app.kubernetes.io/name: affine
spec:
  selector:
    app.kubernetes.io/name: affine
  type: LoadBalancer
  loadBalancerIP: 192.168.10.228
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 13010
      targetPort: 3010
      name: app
