apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: nri-bundle
    repo: https://helm-charts.newrelic.com
    version: 6.0.22
    releaseName: nri-bundle
    valuesFile: values.yaml