apiVersion: v1
kind: Service
metadata:
  name: mathesar
  namespace: mathesar
  labels:
    app.kubernetes.io/name: mathesar
spec:
  selector:
    app.kubernetes.io/name: mathesar
  type: LoadBalancer
  loadBalancerIP: 192.168.10.226
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 8000
      name: web
