apiVersion: v1
kind: Service
metadata:
  name: pgvector
  namespace: pgvector
  labels:
    app.kubernetes.io/name: pgvector
spec:
  selector:
    app.kubernetes.io/name: pgvector
  type: LoadBalancer
  loadBalancerIP: 192.168.10.227
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 15432
      targetPort: 5432
      name: db
